POST http://localhost:4400/user/register
Content-Type: application/json

{
    "firstName": "Robinson",
    "lastName":"Ngecu",
    "email": "robinson.ngecu@thejitu.com",
    "cohortNumber": 7,
    "password": "I@mrich254"
}


###
GET http://localhost:4400/user/a55daeb0-2d83-4c4f-9bba-c722c4de195c
Content-Type: application/json


###
PUT http://localhost:4400/user/a55daeb0-2d83-4c4f-9bba-c722c4de195c
Content-Type: application/json


{
    "firstName": "Jenniffer",
    "lastName":"Kalunda",
    "email": "robinson.ngecu@thejitu.com",
    "cohortNumber": 7
}

###
DELETE http://localhost:4400/user/4098b7ca-4cd3-42f0-9504-78d94f59f162
Content-Type: application/json

{
    "isDeleted": true
}